### ISSUE TITLE
Implementación del despliegue en Docker

### ISSUE THREAD

**Issue by uo283840** [Arquisoft/lomap_es6b#173]

**Comment by aliciafp15** [comment]
Creada una máquina virtual en Azure para el despliegue. Keys ya incluida en GitHub secrets. No se pudo probar el funcionamiento correcto por errores en el árbol de dependencias. Por corregir.

**Comment by manlopdev** [comment]
Finalmente, hemos decidido desplegar la aplicación en GH-Pages.
