### ISSUE TITLE
Comprobar calidad de código con SONAR

### ISSUE THREAD

**Issue by uo283840** [Arquisoft/lomap_es6b#197]

**Comment by uo283840** [comment]
Commits: bac02987077334f6e8a3ed2feaaa56388df29bbf, 2d63918bdf87dcbb0bed8d5fe5d39d24e094a746, 94b45e87edd3b43cf198ab16443dfd3f4161bd4a

**Comment by aliciafp15** [comment]
Commits: b70f55d9af4cb633a5b006299fa6d827aeb26a25 , 85921bc4b5088902a8383638df5ead5e2ae4001a

**Comment by manlopdev** [comment]
commit 85fc4cd120cd814a3a3dc16af016f94c5df5c00a
